// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leqhtrzyoxhfxqikljoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlcWh0cnp5b3hoZnhxaWtsam9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDM2MzUsImV4cCI6MjA2OTYxOTYzNX0.jw4T9gjFDIot0vUFgrDbXNfrqOV4uG6wrFdqsO-hBoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});